<?php
/**
 * Données initiales : services, catégories, réalisations, blocs de contenu, technologies.
 * Tout est ensuite modifiable depuis le back-office.
 */

return [

    /* ------------------------------------------------------------------ */
    'services' => [
        [
            'name' => 'Création de sites Web',
            'slug' => 'creation-site-web',
            'eyebrow' => '01 — Web',
            'icon' => 'web',
            'short_description' => 'Sites modernes, rapides, responsive et conçus pour répondre aux objectifs de votre entreprise.',
            'description' => "<p>Votre site web est souvent le premier contact avec vos clients. Nous concevons des sites <strong>modernes, rapides et pensés pour convertir</strong> : une identité soignée, une navigation claire et des appels à l'action visibles.</p>\n<h2>Des sites qui travaillent pour vous</h2>\n<p>Chaque site est développé sur mesure, optimisé pour le référencement naturel (SEO), parfaitement responsive et administrable : vous gardez la main sur vos contenus sans dépendre d'un développeur.</p>\n<h3>Ce que nous livrons</h3>\n<ul><li>Design UX/UI sur mesure, aligné sur votre identité</li><li>Intégration responsive mobile-first</li><li>Back-office administrateur pour gérer vos contenus</li><li>Optimisation SEO et performances</li><li>Hébergement, mise en ligne et maintenance</li></ul>",
            'items' => "Site vitrine\nSite institutionnel\nE-commerce\nPortail professionnel\nPlateforme web\nEspace client\nBack-office administrateur",
            'cta_label' => 'Découvrir',
            'seo_title' => 'Création de sites web sur mesure — Vitrine, e-commerce, portail | NEOSEN',
            'seo_description' => 'Conception et développement de sites web modernes, responsive et administrables : sites vitrines, institutionnels, e-commerce et plateformes web.',
        ],
        [
            'name' => 'Logiciels & Applications',
            'slug' => 'logiciels-applications',
            'eyebrow' => '02 — Software',
            'icon' => 'app',
            'short_description' => 'Nous concevons des solutions digitales sur mesure adaptées à vos processus et à vos utilisateurs.',
            'description' => "<p>Vos processus métier sont uniques : vos outils devraient l'être aussi. Nous concevons des <strong>applications web, mobiles et logiciels métiers</strong> qui automatisent vos tâches, fluidifient le travail de vos équipes et améliorent l'expérience de vos clients.</p>\n<h2>Du besoin au produit</h2>\n<p>Ateliers de cadrage, maquettes interactives, développement itératif, tests et déploiement : nous construisons avec vous une solution robuste, sécurisée et évolutive.</p>\n<h3>Exemples de réalisations</h3>\n<ul><li>Plateformes SaaS (SIRH, gestion commerciale…)</li><li>Applications mobiles iOS / Android</li><li>Marketplaces et plateformes communautaires</li><li>Outils de gestion internes et tableaux de bord</li><li>API et intégrations avec vos outils existants</li></ul>",
            'items' => "Applications web\nApplications mobiles\nLogiciels métiers\nPlateformes SaaS\nApplications de gestion\nMarketplaces\nPlateformes communautaires\nSolutions sur mesure",
            'cta_label' => 'Découvrir',
            'seo_title' => 'Développement de logiciels et applications sur mesure | NEOSEN',
            'seo_description' => 'Applications web et mobiles, logiciels métiers, SaaS et marketplaces : NEOSEN conçoit des solutions digitales adaptées à vos processus.',
        ],
        [
            'name' => 'Data & Business Intelligence',
            'slug' => 'data-business-intelligence',
            'eyebrow' => '03 — Data',
            'icon' => 'data',
            'short_description' => 'Transformez vos données en informations utiles à la décision.',
            'description' => "<p>Vos données sont dispersées entre ERP, CRM, fichiers Excel et applications métiers ? Nous les <strong>centralisons, fiabilisons et transformons en indicateurs</strong> clairs pour piloter votre activité.</p>\n<h2>Une expertise orientée Microsoft BI</h2>\n<p>Intégration de données avec SSIS, modélisation en étoile dans un Data Warehouse SQL Server, optimisation des requêtes et restitution dans Power BI : nous maîtrisons l'ensemble de la chaîne décisionnelle.</p>\n<h3>Nos interventions</h3>\n<ul><li>Audit de l'existant et cadrage des indicateurs</li><li>Mise en place de flux ETL / ELT automatisés</li><li>Conception de Data Warehouse et modèles analytiques</li><li>Optimisation SQL Server et performances</li><li>Tableaux de bord Power BI et reporting</li></ul>",
            'items' => "Intégration de données\nETL / ELT\nSQL Server\nSSIS\nData Warehouse\nModélisation\nPower BI\nReporting",
            'cta_label' => 'Découvrir',
            'seo_title' => 'Data & Business Intelligence — SSIS, SQL Server, Power BI | NEOSEN',
            'seo_description' => 'Intégration de données, ETL, Data Warehouse, modélisation, optimisation SQL Server et tableaux de bord Power BI.',
        ],
    ],

    /* ------------------------------------------------------------------ */
    'categories' => [
        ['name' => 'Web', 'slug' => 'web'],
        ['name' => 'Application', 'slug' => 'application'],
        ['name' => 'Plateforme', 'slug' => 'plateforme'],
        ['name' => 'Data', 'slug' => 'data'],
    ],

    /* ------------------------------------------------------------------ */
    'projects' => [
        [
            'name' => 'BADGEL',
            'slug' => 'badgel',
            'category' => 'application',
            'category_label' => 'Logiciel / SaaS / SIRH',
            'client' => 'BADGEL',
            'url' => 'https://badgel.sn/',
            'year' => 2025,
            'is_featured' => 1,
            'short_description' => "Conception d'une plateforme SIRH adaptée aux besoins des entreprises sénégalaises, intégrant gestion RH, pointage, congés et paie.",
            'long_description' => "<p>BADGEL est une solution SIRH complète destinée aux entreprises sénégalaises. La plateforme centralise l'ensemble de la gestion des ressources humaines : pointage des salariés, dossiers du personnel, congés, paie légale, entretiens annuels et recrutement.</p><p>Pensée pour les réalités locales, elle intègre les spécificités du Code du Travail sénégalais et les cotisations obligatoires (IPRES, CSS, IR, TRIMF), avec une application mobile dédiée aux salariés.</p>",
            'need' => "Les entreprises sénégalaises gèrent souvent leurs RH avec des fichiers Excel, des registres papier et des logiciels de paie non adaptés à la législation locale. Il fallait un outil unique, simple à déployer, capable de fiabiliser le pointage et d'automatiser une paie conforme.",
            'solution' => "NEOSEN a conçu une plateforme SaaS modulaire : pointage multi-technologies (QR code, NFC, RFID), dossier salarié digitalisé, workflow de congés, moteur de paie intégrant les règles sénégalaises, modules d'entretiens et de recrutement, et un espace employé accessible sur mobile.",
            'features' => "Pointage QR / NFC / RFID\nGestion des salariés et dossier du personnel\nGestion des congés et absences\nPaie conforme (IPRES, CSS, IR, TRIMF)\nEntretiens annuels\nRecrutement\nEspace employé et application mobile\nTableaux de bord RH",
            'results' => "Une plateforme métier complète qui digitalise l'ensemble du cycle RH, réduit drastiquement le temps consacré à la paie et fiabilise le suivi du temps de travail.",
            'technologies' => 'PHP, MySQL, JavaScript, API REST, React Native, HTML5, CSS3',
            'images' => ['badgel-1.webp', 'badgel-2.webp', 'badgel-3.webp', 'badgel-4.webp', 'badgel-mobile.webp'],
        ],
        [
            'name' => 'EKTO SEN',
            'slug' => 'ekto-sen',
            'category' => 'plateforme',
            'category_label' => 'Web / Plateforme',
            'client' => 'EKTO SEN — Kayor',
            'url' => 'https://ektosen.com/',
            'year' => 2025,
            'is_featured' => 1,
            'short_description' => "Développement de Kayor, une plateforme de gestion commerciale pensée pour les PME et distributeurs sénégalais : devis, factures conformes, stock, achats et SAV.",
            'long_description' => "<p>EKTO SEN porte Kayor, un logiciel de gestion commerciale en ligne conçu pour les PME et les distributeurs de matériel au Sénégal. La plateforme réunit dans un seul outil les devis, la facturation conforme, la gestion des stocks, les achats, le service après-vente et le suivi des paiements.</p><p>Elle est adaptée à la fiscalité locale (NINEA, RCCM, TVA) et aux moyens de paiement utilisés au quotidien, comme Wave et Orange Money.</p>",
            'need' => "Les PME et distributeurs jonglaient entre plusieurs outils et fichiers pour leurs devis, factures et stocks, avec un risque d'erreurs et de non-conformité fiscale. Ils avaient besoin d'une solution simple, accessible sans installation et adaptée à leur marché.",
            'solution' => "NEOSEN a développé une plateforme web complète et un site de présentation orienté conversion : modules commerciaux interconnectés, documents conformes générés automatiquement, tableau de bord d'activité en temps réel et offres d'abonnement claires.",
            'features' => "Devis et factures conformes (NINEA / RCCM / TVA)\nGestion des stocks et alertes\nAchats et fournisseurs\nService après-vente (SAV)\nSuivi des paiements Wave & Orange Money\nTableau de bord en temps réel\nGestion des offres et abonnements\nSite vitrine orienté conversion",
            'results' => "Une solution prête pour la sous-région UEMOA qui permet de créer une facture en quelques minutes, sans installation, et de piloter l'activité commerciale depuis un seul tableau de bord.",
            'technologies' => 'PHP, MySQL, JavaScript, HTML5, CSS3, API REST',
            'images' => ['ektosen-1.webp', 'ektosen-2.webp', 'ektosen-3.webp', 'ektosen-4.webp', 'ektosen-mobile.webp'],
        ],
        [
            'name' => 'EXTRIUME',
            'slug' => 'extriume',
            'category' => 'web',
            'category_label' => 'Site institutionnel / Groupe technologique',
            'client' => 'EXTRIUME',
            'url' => 'https://extriume.com/',
            'year' => 2025,
            'is_featured' => 1,
            'short_description' => "Conception d'un site institutionnel moderne permettant de présenter un groupe technologique et ses différents pôles d'activités.",
            'long_description' => "<p>EXTRIUME est un groupe technologique multi-activités, présent dans l'éducation, le digital, la mobilité internationale, la marketplace, la domotique et les services événementiels.</p><p>Le site institutionnel devait refléter cette diversité tout en affirmant une identité forte et premium, résumée par la signature « Let's glow up ».</p>",
            'need' => "Présenter clairement un groupe aux activités très variées, sans perdre le visiteur, et donner à chaque pôle (Fylly, Marketplace, Préinscription, Domotique, Web-App, Services) une visibilité propre.",
            'solution' => "NEOSEN a conçu un site immersif à l'univers sombre et lumineux : animations soignées, présentation structurée des pôles d'activités, arguments différenciants et parcours de contact simplifié.",
            'features' => "Présentation du groupe et de sa vision\nPages et cartes dédiées à chaque pôle d'activité\nDirection artistique immersive et animations\nDesign responsive mobile-first\nFormulaire de contact\nOptimisation SEO",
            'results' => "Une vitrine institutionnelle qui valorise l'image de marque du groupe et oriente efficacement chaque visiteur vers le pôle qui le concerne.",
            'technologies' => 'PHP, MySQL, JavaScript, HTML5, CSS3',
            'images' => ['extriume-1.webp', 'extriume-2.webp', 'extriume-3.webp', 'extriume-4.webp', 'extriume-mobile.webp'],
        ],
        [
            'name' => 'LINK2VEST',
            'slug' => 'link2vest',
            'category' => 'plateforme',
            'category_label' => 'Plateforme Web / FinTech',
            'client' => 'Link2Vest',
            'url' => 'https://link2vest.com/',
            'year' => 2025,
            'is_featured' => 0,
            'short_description' => "Développement d'une plateforme digitale dédiée à l'investissement et au financement de projets au Sénégal.",
            'long_description' => "<p>Link2Vest est une plateforme de crowdfunding et d'investissement qui met en relation les investisseurs et les porteurs de projets au Sénégal, autour de la promesse « Investir aujourd'hui, bâtir demain ».</p><p>Elle propose des parcours distincts pour les investisseurs et les entrepreneurs, un catalogue de projets par secteur, des contenus de formation et un accompagnement par des mentors.</p>",
            'need' => "Créer un environnement de confiance pour financer des projets locaux : présentation transparente des projets, parcours d'inscription sécurisés, vérification des utilisateurs et suivi des investissements.",
            'solution' => "NEOSEN a développé une plateforme complète avec espaces investisseurs et entrepreneurs, gestion des projets par secteur, vérification KYC, paiements via Wave, Orange Money ou carte bancaire, et tableaux de bord de suivi.",
            'features' => "Espace investisseur\nEspace entrepreneur et dépôt de projets\nCatalogue de projets par secteur\nVérification d'identité (KYC)\nPaiements Wave, Orange Money et carte bancaire\nTableau de bord de suivi des investissements\nFormations, articles et mentors\nMulti-devises (CFA, EUR, USD)",
            'results' => "Une plateforme FinTech qui démocratise l'investissement dans l'économie réelle sénégalaise, avec des parcours clairs pour chaque type d'utilisateur.",
            'technologies' => 'PHP, MySQL, JavaScript, API REST, HTML5, CSS3',
            'images' => ['link2vest-1.webp', 'link2vest-2.webp', 'link2vest-3.webp', 'link2vest-4.webp', 'link2vest-mobile.webp'],
        ],
        [
            'name' => 'EASY-GROUPAGE',
            'slug' => 'easy-groupage',
            'category' => 'plateforme',
            'category_label' => 'Plateforme Web / Logistique',
            'client' => 'Easy-Groupage',
            'url' => 'https://easy-groupage.ch/',
            'year' => 2025,
            'is_featured' => 0,
            'short_description' => "Conception d'une plateforme digitale dédiée au transport, au groupage et au suivi des expéditions entre l'Europe et le Sénégal.",
            'long_description' => "<p>Easy-Groupage est une entreprise de services logistiques spécialisée dans les envois entre la Suisse, l'Europe et le Sénégal : fret aérien et maritime en groupage, déménagements internationaux, nationaux et locaux, et transport de véhicules.</p>",
            'need' => "Permettre aux clients de comprendre rapidement les services proposés, d'obtenir un devis sans friction et de suivre leurs colis en toute autonomie, tout en réduisant les demandes répétitives au service client.",
            'solution' => "NEOSEN a conçu une plateforme claire et rassurante : présentation des services et destinations, parcours de demande de devis en 3 étapes (Demande, Devis, Réservation) et module de suivi des colis.",
            'features' => "Fret aérien et maritime en groupage\nDéménagement international, national et local\nTransport de véhicules\nParcours de demande de devis en 3 étapes\nSuivi des colis en ligne\nPrésentation des destinations\nGalerie et contenus rassurants",
            'results' => "Un parcours client fluide, de la demande de devis au suivi de l'expédition, qui renforce la confiance et automatise une partie de la relation client.",
            'technologies' => 'PHP, MySQL, JavaScript, HTML5, CSS3',
            'images' => ['easy-groupage-1.webp', 'easy-groupage-2.webp', 'easy-groupage-3.webp', 'easy-groupage-4.webp', 'easy-groupage-mobile.webp'],
        ],
    ],

    /* ------------------------------------------------------------------ */
    'blocks' => [
        'approach' => [
            ['title' => 'Comprendre', 'subtitle' => '01', 'icon' => 'search', 'description' => 'Analyse du besoin, des objectifs et des contraintes.'],
            ['title' => 'Concevoir', 'subtitle' => '02', 'icon' => 'pen', 'description' => 'Conception fonctionnelle, technique et UX/UI.'],
            ['title' => 'Développer', 'subtitle' => '03', 'icon' => 'code', 'description' => 'Développement de la solution et intégration des fonctionnalités.'],
            ['title' => 'Tester', 'subtitle' => '04', 'icon' => 'test', 'description' => 'Tests, corrections, optimisation et validation.'],
            ['title' => 'Déployer', 'subtitle' => '05', 'icon' => 'rocket', 'description' => 'Mise en production et accompagnement.'],
            ['title' => 'Faire évoluer', 'subtitle' => '06', 'icon' => 'refresh', 'description' => 'Maintenance, amélioration et ajout de nouvelles fonctionnalités.'],
        ],
        'why' => [
            ['title' => 'Une approche sur mesure', 'icon' => 'puzzle', 'description' => 'Chaque projet est conçu en fonction des besoins réels du client.'],
            ['title' => 'Une double expertise', 'icon' => 'layers', 'description' => 'Développement logiciel et Data / BI : des solutions complètes, de l\'interface jusqu\'aux indicateurs.'],
            ['title' => 'Des solutions évolutives', 'icon' => 'trending', 'description' => 'Les solutions sont conçues pour pouvoir évoluer avec votre entreprise.'],
            ['title' => 'Une approche orientée utilisateur', 'icon' => 'users', 'description' => 'L\'expérience utilisateur est au centre de la conception.'],
            ['title' => 'Une vision business', 'icon' => 'target', 'description' => 'L\'objectif n\'est pas simplement de développer une solution, mais de répondre à un besoin métier.'],
            ['title' => 'Un accompagnement continu', 'icon' => 'handshake', 'description' => 'De la conception à la mise en production, puis tout au long des évolutions futures.'],
        ],
        'stats' => [
            ['title' => '3', 'subtitle' => 'expertises complémentaires'],
            ['title' => '5+', 'subtitle' => 'plateformes en production'],
            ['title' => '100%', 'subtitle' => 'solutions sur mesure'],
            ['title' => '48h', 'subtitle' => 'pour une première réponse'],
        ],
        'data_offer' => [
            ['title' => 'Intégration de données', 'icon' => 'flow', 'description' => 'Collecter, transformer et charger vos données de manière fiable et automatisée.', 'items' => "ETL / ELT\nSSIS\nFlux de données\nAutomatisation\nContrôle qualité\nGestion des erreurs"],
            ['title' => 'Modélisation', 'icon' => 'cube', 'description' => 'Structurer vos données pour l\'analyse et garantir des indicateurs cohérents.', 'items' => "Data Warehouse\nSchémas en étoile\nTables de faits\nDimensions\nSCD\nModèles analytiques"],
            ['title' => 'SQL / Bases de données', 'icon' => 'database', 'description' => 'Des bases performantes, sécurisées et optimisées pour vos usages.', 'items' => "SQL Server\nRequêtes SQL\nOptimisation\nIndexation\nProcédures stockées\nPerformance"],
            ['title' => 'Restitution', 'icon' => 'chart', 'description' => 'Des tableaux de bord clairs pour décider vite et bien.', 'items' => "Power BI\nDashboards\nKPI\nReporting\nData visualisation"],
        ],
        'about_values' => [
            ['title' => 'Exigence', 'icon' => 'star', 'description' => 'Un code propre, des interfaces soignées et des livrables testés.'],
            ['title' => 'Transparence', 'icon' => 'eye', 'description' => 'Un suivi clair à chaque étape, des délais et des coûts maîtrisés.'],
            ['title' => 'Proximité', 'icon' => 'handshake', 'description' => 'Un interlocuteur dédié qui comprend vos enjeux et parle votre langage.'],
        ],
    ],

    /* ------------------------------------------------------------------ */
    'technologies' => [
        'Web'    => ['HTML5', 'CSS3', 'JavaScript', 'PHP', 'MySQL'],
        'Mobile' => ['React Native', 'Capacitor', 'API REST'],
        'Data'   => ['SQL Server', 'SSIS', 'Power BI', 'Data Warehouse', 'SQL'],
    ],
];
